* Encoding: UTF-8.

*** SOCIODEMOGRAFICOS***

FREQUENCIES VARIABLES=DSoc_01 DSoc_02 DSoc_04 DSoc_05 DSoc_06 DSan_07 DSan_10 DSan_12.0 
    PMG_23_MESES_TOTAL
  /STATISTICS=STDDEV MEAN
  /ORDER=ANALYSIS.

T-TEST GROUPS=PROGRAMA(1 2)
  /MISSING=ANALYSIS
  /VARIABLES=DSoc_02 PMG_23_MESES_TOTAL
  /CRITERIA=CI(.95).

CROSSTABS
  /TABLES=PROGRAMA BY DSoc_01 DSoc_04 DSoc_05 DSoc_06 DSan_07 DSan_10 DSan_12.0 
  /FORMAT=AVALUE TABLES
  /STATISTICS=CHISQ 
  /CELLS=COUNT ROW COLUMN TOTAL 
  /COUNT ROUND CELL.

***T2ACC filter T1_tiempo PRE / POST + grupo***

GLM MeanResponse2.ACCAngryAngry2_T2ACCfilterT1_PRE MeanResponse2.ACCAngryAngry4_T2ACCfilterT1_PRE 
    MeanResponse2.ACCAngryAngry6_T2ACCfilterT1_PRE MeanResponse2.ACCAngryHappy2_T2ACCfilterT1_PRE 
    MeanResponse2.ACCAngryHappy4_T2ACCfilterT1_PRE MeanResponse2.ACCAngryHappy6_T2ACCfilterT1_PRE 
    MeanResponse2.ACCAngryNeutral2_T2ACCfilterT1_PRE MeanResponse2.ACCAngryNeutral4_T2ACCfilterT1_PRE 
    MeanResponse2.ACCAngryNeutral6_T2ACCfilterT1_PRE MeanResponse2.ACCHappyAngry2_T2ACCfilterT1_PRE 
    MeanResponse2.ACCHappyAngry4_T2ACCfilterT1_PRE MeanResponse2.ACCHappyAngry6_T2ACCfilterT1_PRE 
    MeanResponse2.ACCHappyHappy2_T2ACCfilterT1_PRE MeanResponse2.ACCHappyHappy4_T2ACCfilterT1_PRE 
    MeanResponse2.ACCHappyHappy6_T2ACCfilterT1_PRE MeanResponse2.ACCHappyNeutral2_T2ACCfilterT1_PRE 
    MeanResponse2.ACCHappyNeutral4_T2ACCfilterT1_PRE MeanResponse2.ACCHappyNeutral6_T2ACCfilterT1_PRE 
    MeanResponse2.ACCNeutralAngry2_T2ACCfilterT1_PRE MeanResponse2.ACCNeutralAngry4_T2ACCfilterT1_PRE 
    MeanResponse2.ACCNeutralAngry6_T2ACCfilterT1_PRE MeanResponse2.ACCNeutralHappy2_T2ACCfilterT1_PRE 
    MeanResponse2.ACCNeutralHappy4_T2ACCfilterT1_PRE MeanResponse2.ACCNeutralHappy6_T2ACCfilterT1_PRE 
    MeanResponse2.ACCNeutralNeutral2_T2ACCfilterT1_PRE MeanResponse2.ACCNeutralNeutral4_T2ACCfilterT1_PRE 
    MeanResponse2.ACCNeutralNeutral6_T2ACCfilterT1_PRE MeanResponse2.ACCAngryAngry2_T2ACCfilterT1_POST 
    MeanResponse2.ACCAngryAngry4_T2ACCfilterT1_POST MeanResponse2.ACCAngryAngry6_T2ACCfilterT1_POST 
    MeanResponse2.ACCAngryHappy2_T2ACCfilterT1_POST MeanResponse2.ACCAngryHappy4_T2ACCfilterT1_POST 
    MeanResponse2.ACCAngryHappy6_T2ACCfilterT1_POST MeanResponse2.ACCAngryNeutral2_T2ACCfilterT1_POST 
    MeanResponse2.ACCAngryNeutral4_T2ACCfilterT1_POST MeanResponse2.ACCAngryNeutral6_T2ACCfilterT1_POST 
    MeanResponse2.ACCHappyAngry2_T2ACCfilterT1_POST MeanResponse2.ACCHappyAngry4_T2ACCfilterT1_POST 
    MeanResponse2.ACCHappyAngry6_T2ACCfilterT1_POST MeanResponse2.ACCHappyHappy2_T2ACCfilterT1_POST 
    MeanResponse2.ACCHappyHappy4_T2ACCfilterT1_POST MeanResponse2.ACCHappyHappy6_T2ACCfilterT1_POST 
    MeanResponse2.ACCHappyNeutral2_T2ACCfilterT1_POST MeanResponse2.ACCHappyNeutral4_T2ACCfilterT1_POST 
    MeanResponse2.ACCHappyNeutral6_T2ACCfilterT1_POST MeanResponse2.ACCNeutralAngry2_T2ACCfilterT1_POST 
    MeanResponse2.ACCNeutralAngry4_T2ACCfilterT1_POST MeanResponse2.ACCNeutralAngry6_T2ACCfilterT1_POST 
    MeanResponse2.ACCNeutralHappy2_T2ACCfilterT1_POST MeanResponse2.ACCNeutralHappy4_T2ACCfilterT1_POST 
    MeanResponse2.ACCNeutralHappy6_T2ACCfilterT1_POST MeanResponse2.ACCNeutralNeutral2_T2ACCfilterT1_POST 
    MeanResponse2.ACCNeutralNeutral4_T2ACCfilterT1_POST 
    MeanResponse2.ACCNeutralNeutral6_T2ACCfilterT1_POST BY PROGRAMA
  /WSFACTOR=Tiempo 2 Polynomial EmoT1 3 Polynomial EmoT2 3 Polynomial Lag 3 Polynomial 
  /CONTRAST(PROGRAMA)=Simple
  /METHOD=SSTYPE(3)
  /PLOT=PROFILE(Lag*EmoT1*EmoT2 Lag*EmoT2*EmoT1 Lag*EmoT1*Tiempo Lag*EmoT2*Tiempo 
    Lag*EmoT2*PROGRAMA Lag*PROGRAMA*Tiempo EmoT2*Tiempo*PROGRAMA Lag*Tiempo*PROGRAMA)
  /EMMEANS=TABLES(OVERALL) 
  /EMMEANS=TABLES(Tiempo) COMPARE ADJ(BONFERRONI)
  /EMMEANS=TABLES(EmoT1) COMPARE ADJ(BONFERRONI)
  /EMMEANS=TABLES(EmoT2) COMPARE ADJ(BONFERRONI)
  /EMMEANS=TABLES(Lag) COMPARE ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo*EmoT1) COMPARE (Tiempo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo*EmoT1) COMPARE (EmoT1) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo*EmoT2) COMPARE (Tiempo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo*EmoT2) COMPARE (EmoT2) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo*Lag) COMPARE (Tiempo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo*Lag) COMPARE (Lag) ADJ(BONFERRONI)
  /EMMEANS=TABLES(EmoT1*EmoT2) COMPARE (EmoT1) ADJ(BONFERRONI)
  /EMMEANS=TABLES(EmoT1*EmoT2) COMPARE (EmoT2) ADJ(BONFERRONI)
  /EMMEANS=TABLES(EmoT1*Lag) COMPARE (EmoT1) ADJ(BONFERRONI)
  /EMMEANS=TABLES(EmoT1*Lag) COMPARE (Lag) ADJ(BONFERRONI)
  /EMMEANS=TABLES(EmoT2*Lag) COMPARE (EmoT2) ADJ(BONFERRONI)
  /EMMEANS=TABLES(EmoT2*Lag) COMPARE (Lag) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo*EmoT1*EmoT2) COMPARE (Tiempo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo*EmoT1*EmoT2) COMPARE (EmoT1) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo*EmoT1*EmoT2) COMPARE (EmoT2) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo*EmoT1*Lag) COMPARE (Tiempo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo*EmoT1*Lag) COMPARE (EmoT1) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo*EmoT1*Lag) COMPARE (Lag) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo*EmoT2*Lag) COMPARE (Tiempo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo*EmoT2*Lag) COMPARE (EmoT2) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo*EmoT2*Lag) COMPARE (Lag) ADJ(BONFERRONI)
  /EMMEANS=TABLES(EmoT1*EmoT2*Lag) COMPARE (EmoT1) ADJ(BONFERRONI)
  /EMMEANS=TABLES(EmoT1*EmoT2*Lag) COMPARE (EmoT2) ADJ(BONFERRONI)
  /EMMEANS=TABLES(EmoT1*EmoT2*Lag) COMPARE (Lag) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo*EmoT1*EmoT2*Lag) COMPARE (Tiempo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo*EmoT1*EmoT2*Lag) COMPARE (EmoT1) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo*EmoT1*EmoT2*Lag) COMPARE (EmoT2) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo*EmoT1*EmoT2*Lag) COMPARE (Lag) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA) COMPARE ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo) COMPARE (PROGRAMA) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo) COMPARE (Tiempo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*EmoT1) COMPARE (PROGRAMA) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*EmoT1) COMPARE (EmoT1) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*EmoT2) COMPARE (PROGRAMA) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*EmoT2) COMPARE (EmoT2) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Lag) COMPARE (PROGRAMA) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Lag) COMPARE (Lag) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT1) COMPARE (PROGRAMA) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT1) COMPARE (Tiempo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT1) COMPARE (EmoT1) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT2) COMPARE (PROGRAMA) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT2) COMPARE (Tiempo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT2) COMPARE (EmoT2) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*Lag) COMPARE (PROGRAMA) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*Lag) COMPARE (Tiempo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*Lag) COMPARE (Lag) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*EmoT1*EmoT2) COMPARE (PROGRAMA) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*EmoT1*EmoT2) COMPARE (EmoT1) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*EmoT1*EmoT2) COMPARE (EmoT2) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*EmoT1*Lag) COMPARE (PROGRAMA) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*EmoT1*Lag) COMPARE (EmoT1) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*EmoT1*Lag) COMPARE (Lag) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*EmoT2*Lag) COMPARE (PROGRAMA) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*EmoT2*Lag) COMPARE (EmoT2) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*EmoT2*Lag) COMPARE (Lag) ADJ(BONFERRONI) 
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT1*EmoT2) COMPARE (PROGRAMA) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT1*EmoT2) COMPARE (Tiempo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT1*EmoT2) COMPARE (EmoT1) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT1*EmoT2) COMPARE (EmoT2) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT1*Lag) COMPARE (PROGRAMA) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT1*Lag) COMPARE (Tiempo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT1*Lag) COMPARE (EmoT1) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT1*Lag) COMPARE (Lag) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT2*Lag) COMPARE (PROGRAMA) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT2*Lag) COMPARE (Tiempo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT2*Lag) COMPARE (EmoT2) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT2*Lag) COMPARE (Lag) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*EmoT1*EmoT2*Lag) COMPARE (PROGRAMA) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*EmoT1*EmoT2*Lag) COMPARE (EmoT1) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*EmoT1*EmoT2*Lag) COMPARE (EmoT2) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*EmoT1*EmoT2*Lag) COMPARE (Lag) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT1*EmoT2*Lag) COMPARE (PROGRAMA) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT1*EmoT2*Lag) COMPARE (Tiempo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT1*EmoT2*Lag) COMPARE (EmoT1) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT1*EmoT2*Lag) COMPARE (EmoT2) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT1*EmoT2*Lag) COMPARE (Lag) ADJ(BONFERRONI)
  /PRINT=DESCRIPTIVE ETASQ OPOWER HOMOGENEITY 
  /CRITERIA=ALPHA(.05)
  /WSDESIGN=Tiempo EmoT1 EmoT2 Lag Tiempo*EmoT1 Tiempo*EmoT2 EmoT1*EmoT2 Tiempo*EmoT1*EmoT2 
    Tiempo*Lag EmoT1*Lag Tiempo*EmoT1*Lag EmoT2*Lag Tiempo*EmoT2*Lag EmoT1*EmoT2*Lag 
    Tiempo*EmoT1*EmoT2*Lag
  /DESIGN=PROGRAMA.

***T2ACC_filterT1_ ANOVA 2 (tiempo) x 3 (EmoT2) x 3 (lag) x 2 (grupo) para las T1 angry***

GLM MeanResponse2.ACCAngryAngry2_T2ACCfilterT1_PRE MeanResponse2.ACCAngryAngry4_T2ACCfilterT1_PRE 
    MeanResponse2.ACCAngryAngry6_T2ACCfilterT1_PRE MeanResponse2.ACCAngryHappy2_T2ACCfilterT1_PRE 
    MeanResponse2.ACCAngryHappy4_T2ACCfilterT1_PRE MeanResponse2.ACCAngryHappy6_T2ACCfilterT1_PRE 
    MeanResponse2.ACCAngryNeutral2_T2ACCfilterT1_PRE MeanResponse2.ACCAngryNeutral4_T2ACCfilterT1_PRE 
    MeanResponse2.ACCAngryNeutral6_T2ACCfilterT1_PRE MeanResponse2.ACCAngryAngry2_T2ACCfilterT1_POST 
    MeanResponse2.ACCAngryAngry4_T2ACCfilterT1_POST MeanResponse2.ACCAngryAngry6_T2ACCfilterT1_POST 
    MeanResponse2.ACCAngryHappy2_T2ACCfilterT1_POST MeanResponse2.ACCAngryHappy4_T2ACCfilterT1_POST 
    MeanResponse2.ACCAngryHappy6_T2ACCfilterT1_POST MeanResponse2.ACCAngryNeutral2_T2ACCfilterT1_POST 
    MeanResponse2.ACCAngryNeutral4_T2ACCfilterT1_POST MeanResponse2.ACCAngryNeutral6_T2ACCfilterT1_POST 
    BY PROGRAMA
  /WSFACTOR=Tiempo 2 Polynomial EmoT2 3 Polynomial Lag 3 Polynomial 
  /CONTRAST(PROGRAMA)=Simple
  /METHOD=SSTYPE(3)
  /PLOT=PROFILE(Lag*PROGRAMA*Tiempo EmoT2*PROGRAMA*Tiempo Tiempo*PROGRAMA*EmoT2 Tiempo*PROGRAMA*Lag)    
  /EMMEANS=TABLES(OVERALL) 
  /EMMEANS=TABLES(PROGRAMA) COMPARE ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo) COMPARE ADJ(BONFERRONI)
  /EMMEANS=TABLES(EmoT2) COMPARE ADJ(BONFERRONI)
  /EMMEANS=TABLES(Lag) COMPARE ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo) COMPARE (PROGRAMA) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo) COMPARE (Tiempo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*EmoT2) COMPARE (PROGRAMA) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*EmoT2) COMPARE (EmoT2) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Lag) COMPARE (PROGRAMA) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Lag) COMPARE (Lag) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo*EmoT2) COMPARE (Tiempo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo*EmoT2) COMPARE (EmoT2) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo*Lag) COMPARE (Tiempo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo*Lag) COMPARE (Lag) ADJ(BONFERRONI)
  /EMMEANS=TABLES(EmoT2*Lag) COMPARE (EmoT2) ADJ(BONFERRONI)
  /EMMEANS=TABLES(EmoT2*Lag) COMPARE (Lag) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT2) COMPARE (PROGRAMA) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT2) COMPARE (Tiempo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT2) COMPARE (EmoT2) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*Lag) COMPARE (PROGRAMA) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*Lag) COMPARE (Tiempo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*Lag) COMPARE (Lag) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*EmoT2*Lag) COMPARE (PROGRAMA) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*EmoT2*Lag) COMPARE (EmoT2) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*EmoT2*Lag) COMPARE (Lag) ADJ(BONFERRONI) 
  /EMMEANS=TABLES(Tiempo*EmoT2*Lag) COMPARE (Tiempo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo*EmoT2*Lag) COMPARE (EmoT2) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo*EmoT2*Lag) COMPARE (Lag) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT2*Lag) COMPARE (PROGRAMA) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT2*Lag) COMPARE (Tiempo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT2*Lag) COMPARE (EmoT2) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT2*Lag) COMPARE (Lag) ADJ(BONFERRONI)
  /PRINT=DESCRIPTIVE ETASQ OPOWER HOMOGENEITY 
  /CRITERIA=ALPHA(.05)
  /WSDESIGN=Tiempo EmoT2 Lag Tiempo*EmoT2 Tiempo*Lag EmoT2*Lag Tiempo*EmoT2*Lag
  /DESIGN=PROGRAMA.

***T2ACC_filterT1_ ANOVA 2 (tiempo) x 3 (EmoT2) x 3 (lag) x 2 (grupo) para las T1 happy***

GLM MeanResponse2.ACCHappyAngry2_T2ACCfilterT1_PRE MeanResponse2.ACCHappyAngry4_T2ACCfilterT1_PRE 
    MeanResponse2.ACCHappyAngry6_T2ACCfilterT1_PRE MeanResponse2.ACCHappyHappy2_T2ACCfilterT1_PRE 
    MeanResponse2.ACCHappyHappy4_T2ACCfilterT1_PRE MeanResponse2.ACCHappyHappy6_T2ACCfilterT1_PRE 
    MeanResponse2.ACCHappyNeutral2_T2ACCfilterT1_PRE MeanResponse2.ACCHappyNeutral4_T2ACCfilterT1_PRE 
    MeanResponse2.ACCHappyNeutral6_T2ACCfilterT1_PRE MeanResponse2.ACCHappyAngry2_T2ACCfilterT1_POST 
    MeanResponse2.ACCHappyAngry4_T2ACCfilterT1_POST MeanResponse2.ACCHappyAngry6_T2ACCfilterT1_POST 
    MeanResponse2.ACCHappyHappy2_T2ACCfilterT1_POST MeanResponse2.ACCHappyHappy4_T2ACCfilterT1_POST 
    MeanResponse2.ACCHappyHappy6_T2ACCfilterT1_POST MeanResponse2.ACCHappyNeutral2_T2ACCfilterT1_POST 
    MeanResponse2.ACCHappyNeutral4_T2ACCfilterT1_POST MeanResponse2.ACCHappyNeutral6_T2ACCfilterT1_POST 
    BY PROGRAMA
  /WSFACTOR=Tiempo 2 Polynomial EmoT2 3 Polynomial Lag 3 Polynomial 
  /CONTRAST(PROGRAMA)=Simple
  /METHOD=SSTYPE(3)
  /PLOT=PROFILE(Lag*PROGRAMA*Tiempo EmoT2*PROGRAMA*Tiempo Tiempo*PROGRAMA*EmoT2 Tiempo*PROGRAMA*Lag)    
  /EMMEANS=TABLES(OVERALL) 
  /EMMEANS=TABLES(PROGRAMA) COMPARE ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo) COMPARE ADJ(BONFERRONI)
  /EMMEANS=TABLES(EmoT2) COMPARE ADJ(BONFERRONI)
  /EMMEANS=TABLES(Lag) COMPARE ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo) COMPARE (PROGRAMA) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo) COMPARE (Tiempo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*EmoT2) COMPARE (PROGRAMA) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*EmoT2) COMPARE (EmoT2) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Lag) COMPARE (PROGRAMA) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Lag) COMPARE (Lag) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo*EmoT2) COMPARE (Tiempo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo*EmoT2) COMPARE (EmoT2) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo*Lag) COMPARE (Tiempo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo*Lag) COMPARE (Lag) ADJ(BONFERRONI)
  /EMMEANS=TABLES(EmoT2*Lag) COMPARE (EmoT2) ADJ(BONFERRONI)
  /EMMEANS=TABLES(EmoT2*Lag) COMPARE (Lag) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT2) COMPARE (PROGRAMA) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT2) COMPARE (Tiempo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT2) COMPARE (EmoT2) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*Lag) COMPARE (PROGRAMA) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*Lag) COMPARE (Tiempo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*Lag) COMPARE (Lag) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*EmoT2*Lag) COMPARE (PROGRAMA) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*EmoT2*Lag) COMPARE (EmoT2) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*EmoT2*Lag) COMPARE (Lag) ADJ(BONFERRONI) 
  /EMMEANS=TABLES(Tiempo*EmoT2*Lag) COMPARE (Tiempo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo*EmoT2*Lag) COMPARE (EmoT2) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo*EmoT2*Lag) COMPARE (Lag) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT2*Lag) COMPARE (PROGRAMA) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT2*Lag) COMPARE (Tiempo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT2*Lag) COMPARE (EmoT2) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT2*Lag) COMPARE (Lag) ADJ(BONFERRONI)
  /PRINT=DESCRIPTIVE ETASQ OPOWER HOMOGENEITY 
  /CRITERIA=ALPHA(.05)
  /WSDESIGN=Tiempo EmoT2 Lag Tiempo*EmoT2 Tiempo*Lag EmoT2*Lag Tiempo*EmoT2*Lag
  /DESIGN=PROGRAMA.

***T2ACC_filterT1_ ANOVA 2 (tiempo) x 3 (EmoT2) x 3 (lag) x 2 (grupo) para las T1 neutra***

GLM MeanResponse2.ACCNeutralAngry2_T2ACCfilterT1_PRE 
    MeanResponse2.ACCNeutralAngry4_T2ACCfilterT1_PRE MeanResponse2.ACCNeutralAngry6_T2ACCfilterT1_PRE 
    MeanResponse2.ACCNeutralHappy2_T2ACCfilterT1_PRE MeanResponse2.ACCNeutralHappy4_T2ACCfilterT1_PRE 
    MeanResponse2.ACCNeutralHappy6_T2ACCfilterT1_PRE MeanResponse2.ACCNeutralNeutral2_T2ACCfilterT1_PRE 
    MeanResponse2.ACCNeutralNeutral4_T2ACCfilterT1_PRE 
    MeanResponse2.ACCNeutralNeutral6_T2ACCfilterT1_PRE 
    MeanResponse2.ACCNeutralAngry2_T2ACCfilterT1_POST MeanResponse2.ACCNeutralAngry4_T2ACCfilterT1_POST 
    MeanResponse2.ACCNeutralAngry6_T2ACCfilterT1_POST MeanResponse2.ACCNeutralHappy2_T2ACCfilterT1_POST 
    MeanResponse2.ACCNeutralHappy4_T2ACCfilterT1_POST MeanResponse2.ACCNeutralHappy6_T2ACCfilterT1_POST 
    MeanResponse2.ACCNeutralNeutral2_T2ACCfilterT1_POST 
    MeanResponse2.ACCNeutralNeutral4_T2ACCfilterT1_POST 
    MeanResponse2.ACCNeutralNeutral6_T2ACCfilterT1_POST BY PROGRAMA
  /WSFACTOR=Tiempo 2 Polynomial EmoT2 3 Polynomial Lag 3 Polynomial 
  /CONTRAST(PROGRAMA)=Simple
  /METHOD=SSTYPE(3)
  /PLOT=PROFILE(Lag*PROGRAMA*Tiempo EmoT2*PROGRAMA*Tiempo Tiempo*PROGRAMA*EmoT2 Tiempo*PROGRAMA*Lag)    
  /EMMEANS=TABLES(OVERALL) 
  /EMMEANS=TABLES(PROGRAMA) COMPARE ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo) COMPARE ADJ(BONFERRONI)
  /EMMEANS=TABLES(EmoT2) COMPARE ADJ(BONFERRONI)
  /EMMEANS=TABLES(Lag) COMPARE ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo) COMPARE (PROGRAMA) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo) COMPARE (Tiempo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*EmoT2) COMPARE (PROGRAMA) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*EmoT2) COMPARE (EmoT2) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Lag) COMPARE (PROGRAMA) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Lag) COMPARE (Lag) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo*EmoT2) COMPARE (Tiempo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo*EmoT2) COMPARE (EmoT2) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo*Lag) COMPARE (Tiempo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo*Lag) COMPARE (Lag) ADJ(BONFERRONI)
  /EMMEANS=TABLES(EmoT2*Lag) COMPARE (EmoT2) ADJ(BONFERRONI)
  /EMMEANS=TABLES(EmoT2*Lag) COMPARE (Lag) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT2) COMPARE (PROGRAMA) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT2) COMPARE (Tiempo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT2) COMPARE (EmoT2) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*Lag) COMPARE (PROGRAMA) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*Lag) COMPARE (Tiempo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*Lag) COMPARE (Lag) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*EmoT2*Lag) COMPARE (PROGRAMA) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*EmoT2*Lag) COMPARE (EmoT2) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*EmoT2*Lag) COMPARE (Lag) ADJ(BONFERRONI) 
  /EMMEANS=TABLES(Tiempo*EmoT2*Lag) COMPARE (Tiempo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo*EmoT2*Lag) COMPARE (EmoT2) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo*EmoT2*Lag) COMPARE (Lag) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT2*Lag) COMPARE (PROGRAMA) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT2*Lag) COMPARE (Tiempo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT2*Lag) COMPARE (EmoT2) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT2*Lag) COMPARE (Lag) ADJ(BONFERRONI)
  /PRINT=DESCRIPTIVE ETASQ OPOWER HOMOGENEITY 
  /CRITERIA=ALPHA(.05)
  /WSDESIGN=Tiempo EmoT2 Lag Tiempo*EmoT2 Tiempo*Lag EmoT2*Lag Tiempo*EmoT2*Lag
  /DESIGN=PROGRAMA.

*************************************************************************************************************************************

***TASK REPRODUCIBILITY***

GLM MeanResponse2.ACCAngryAngry2_T2ACCfilterT1_PRE MeanResponse2.ACCAngryAngry4_T2ACCfilterT1_PRE 
    MeanResponse2.ACCAngryAngry6_T2ACCfilterT1_PRE MeanResponse2.ACCAngryHappy2_T2ACCfilterT1_PRE 
    MeanResponse2.ACCAngryHappy4_T2ACCfilterT1_PRE MeanResponse2.ACCAngryHappy6_T2ACCfilterT1_PRE 
    MeanResponse2.ACCAngryNeutral2_T2ACCfilterT1_PRE MeanResponse2.ACCAngryNeutral4_T2ACCfilterT1_PRE 
    MeanResponse2.ACCAngryNeutral6_T2ACCfilterT1_PRE MeanResponse2.ACCHappyAngry2_T2ACCfilterT1_PRE 
    MeanResponse2.ACCHappyAngry4_T2ACCfilterT1_PRE MeanResponse2.ACCHappyAngry6_T2ACCfilterT1_PRE 
    MeanResponse2.ACCHappyHappy2_T2ACCfilterT1_PRE MeanResponse2.ACCHappyHappy4_T2ACCfilterT1_PRE 
    MeanResponse2.ACCHappyHappy6_T2ACCfilterT1_PRE MeanResponse2.ACCHappyNeutral2_T2ACCfilterT1_PRE 
    MeanResponse2.ACCHappyNeutral4_T2ACCfilterT1_PRE MeanResponse2.ACCHappyNeutral6_T2ACCfilterT1_PRE 
    MeanResponse2.ACCNeutralAngry2_T2ACCfilterT1_PRE MeanResponse2.ACCNeutralAngry4_T2ACCfilterT1_PRE 
    MeanResponse2.ACCNeutralAngry6_T2ACCfilterT1_PRE MeanResponse2.ACCNeutralHappy2_T2ACCfilterT1_PRE 
    MeanResponse2.ACCNeutralHappy4_T2ACCfilterT1_PRE MeanResponse2.ACCNeutralHappy6_T2ACCfilterT1_PRE 
    MeanResponse2.ACCNeutralNeutral2_T2ACCfilterT1_PRE MeanResponse2.ACCNeutralNeutral4_T2ACCfilterT1_PRE 
    MeanResponse2.ACCNeutralNeutral6_T2ACCfilterT1_PRE
  /WSFACTOR=EmoT1 3 Simple EmoT2 3 Simple Lag 3 Simple 
  /METHOD=SSTYPE(3)
  /PLOT=PROFILE(Lag*EmoT1*EmoT2 Lag*EmoT2*EmoT1)
  /EMMEANS=TABLES(OVERALL) 
  /EMMEANS=TABLES(EmoT1) COMPARE ADJ(BONFERRONI)
  /EMMEANS=TABLES(EmoT2) COMPARE ADJ(BONFERRONI)
  /EMMEANS=TABLES(Lag) COMPARE ADJ(BONFERRONI)
  /EMMEANS=TABLES(EmoT1*EmoT2) COMPARE (EmoT1) ADJ(BONFERRONI)
  /EMMEANS=TABLES(EmoT1*EmoT2) COMPARE (EmoT2) ADJ(BONFERRONI)
  /EMMEANS=TABLES(EmoT1*Lag) COMPARE (EmoT1) ADJ(BONFERRONI)
  /EMMEANS=TABLES(EmoT1*Lag) COMPARE (Lag) ADJ(BONFERRONI)
  /EMMEANS=TABLES(EmoT2*Lag) COMPARE (EmoT2) ADJ(BONFERRONI)
  /EMMEANS=TABLES(EmoT2*Lag) COMPARE (Lag) ADJ(BONFERRONI)
  /EMMEANS=TABLES(EmoT1*EmoT2*Lag) COMPARE (EmoT1) ADJ(BONFERRONI)
  /EMMEANS=TABLES(EmoT1*EmoT2*Lag) COMPARE (EmoT2) ADJ(BONFERRONI)
  /EMMEANS=TABLES(EmoT1*EmoT2*Lag) COMPARE (Lag) ADJ(BONFERRONI)
  /PRINT=DESCRIPTIVE ETASQ OPOWER HOMOGENEITY 
  /CRITERIA=ALPHA(.05)
  /WSDESIGN=EmoT1 EmoT2 Lag EmoT1*EmoT2 EmoT1*Lag EmoT2*Lag EmoT1*EmoT2*Lag.

*** ANOVA --> T2 ENSAYOS DOBLES vs ENSAYOS SIMPLES ***

GLM T2_angry_lag6_PRE T2_happy_lag6_PRE T2_neutral_lag6_PRE T2_angry_lag6_POST T2_happy_lag6_POST 
    T2_neutral_lag6_POST MeanResponse2.ACCAngry888888_T2ACCfilterT1_PRE 
    MeanResponse2.ACCHappy888888_T2ACCfilterT1_PRE MeanResponse2.ACCNeutral888888_T2ACCfilterT1_PRE 
    MeanResponse2.ACCAngry888888_T2ACCfilterT1_POST MeanResponse2.ACCHappy888888_T2ACCfilterT1_POST 
    MeanResponse2.ACCNeutral888888_T2ACCfilterT1_POST BY PROGRAMA
  /WSFACTOR=Trial 2 Polynomial Time 2 Polynomial Emo 3 Polynomial 
  /METHOD=SSTYPE(3)
  /PLOT=PROFILE(Time*Trial*PROGRAMA Emo*Trial*PROGRAMA Time*Emo*Trial Time*Emo*PROGRAMA) TYPE=LINE 
    ERRORBAR=CI MEANREFERENCE=YES YAXIS=AUTO
  /EMMEANS=TABLES(OVERALL) 
  /EMMEANS=TABLES(PROGRAMA) COMPARE ADJ(BONFERRONI)
  /EMMEANS=TABLES(Trial) COMPARE ADJ(BONFERRONI)
  /EMMEANS=TABLES(Time) COMPARE ADJ(BONFERRONI)
  /EMMEANS=TABLES(Emo) COMPARE ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Trial) COMPARE (PROGRAMA) ADJ(BONFERRONI)
    /EMMEANS=TABLES(PROGRAMA*Trial) COMPARE (Trial) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Time) COMPARE (PROGRAMA) ADJ(BONFERRONI)
    /EMMEANS=TABLES(PROGRAMA*Time) COMPARE (Time) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Emo) COMPARE (PROGRAMA) ADJ(BONFERRONI)
    /EMMEANS=TABLES(PROGRAMA*Emo) COMPARE (Emo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Trial*Time) COMPARE (Trial) ADJ(BONFERRONI)
    /EMMEANS=TABLES(Trial*Time) COMPARE (Time) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Trial*Emo) COMPARE (Trial) ADJ(BONFERRONI)
    /EMMEANS=TABLES(Trial*Emo) COMPARE (Emo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Time*Emo)  COMPARE (Time) ADJ(BONFERRONI)
    /EMMEANS=TABLES(Time*Emo)  COMPARE (Emo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Trial*Time) COMPARE (PROGRAMA) ADJ(BONFERRONI)
    /EMMEANS=TABLES(PROGRAMA*Trial*Time) COMPARE (Trial) ADJ(BONFERRONI)
        /EMMEANS=TABLES(PROGRAMA*Trial*Time) COMPARE (Time) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Trial*Emo) COMPARE (PROGRAMA) ADJ(BONFERRONI)
    /EMMEANS=TABLES(PROGRAMA*Trial*Emo) COMPARE (Trial) ADJ(BONFERRONI)
      /EMMEANS=TABLES(PROGRAMA*Trial*Emo) COMPARE (Emo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Time*Emo) COMPARE (PROGRAMA) ADJ(BONFERRONI)
    /EMMEANS=TABLES(PROGRAMA*Time*Emo) COMPARE (Time) ADJ(BONFERRONI)
      /EMMEANS=TABLES(PROGRAMA*Time*Emo) COMPARE (Emo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(Trial*Time*Emo) COMPARE (Trial) ADJ(BONFERRONI)
    /EMMEANS=TABLES(Trial*Time*Emo) COMPARE (Time) ADJ(BONFERRONI)
      /EMMEANS=TABLES(Trial*Time*Emo) COMPARE (Emo) ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Trial*Time*Emo) COMPARE (PROGRAMA) ADJ(BONFERRONI)
    /EMMEANS=TABLES(PROGRAMA*Trial*Time*Emo) COMPARE (Trial) ADJ(BONFERRONI)
      /EMMEANS=TABLES(PROGRAMA*Trial*Time*Emo) COMPARE (Time) ADJ(BONFERRONI)
        /EMMEANS=TABLES(PROGRAMA*Trial*Time*Emo) COMPARE (Emo) ADJ(BONFERRONI)
  /PRINT=DESCRIPTIVE ETASQ OPOWER HOMOGENEITY 
  /CRITERIA=ALPHA(.05)
  /WSDESIGN=Trial Time Emo Trial*Time Trial*Emo Time*Emo Trial*Time*Emo
  /DESIGN=PROGRAMA.

***ANCOVA CONTROLANDO EL EFECTO DE LA EDAD ***

GLM MeanResponse2.ACCAngryAngry2_T2ACCfilterT1_PRE MeanResponse2.ACCAngryAngry4_T2ACCfilterT1_PRE 
    MeanResponse2.ACCAngryAngry6_T2ACCfilterT1_PRE MeanResponse2.ACCAngryHappy2_T2ACCfilterT1_PRE 
    MeanResponse2.ACCAngryHappy4_T2ACCfilterT1_PRE MeanResponse2.ACCAngryHappy6_T2ACCfilterT1_PRE 
    MeanResponse2.ACCAngryNeutral2_T2ACCfilterT1_PRE MeanResponse2.ACCAngryNeutral4_T2ACCfilterT1_PRE 
    MeanResponse2.ACCAngryNeutral6_T2ACCfilterT1_PRE MeanResponse2.ACCHappyAngry2_T2ACCfilterT1_PRE 
    MeanResponse2.ACCHappyAngry4_T2ACCfilterT1_PRE MeanResponse2.ACCHappyAngry6_T2ACCfilterT1_PRE 
    MeanResponse2.ACCHappyHappy2_T2ACCfilterT1_PRE MeanResponse2.ACCHappyHappy4_T2ACCfilterT1_PRE 
    MeanResponse2.ACCHappyHappy6_T2ACCfilterT1_PRE MeanResponse2.ACCHappyNeutral2_T2ACCfilterT1_PRE 
    MeanResponse2.ACCHappyNeutral4_T2ACCfilterT1_PRE MeanResponse2.ACCHappyNeutral6_T2ACCfilterT1_PRE 
    MeanResponse2.ACCNeutralAngry2_T2ACCfilterT1_PRE MeanResponse2.ACCNeutralAngry4_T2ACCfilterT1_PRE 
    MeanResponse2.ACCNeutralAngry6_T2ACCfilterT1_PRE MeanResponse2.ACCNeutralHappy2_T2ACCfilterT1_PRE 
    MeanResponse2.ACCNeutralHappy4_T2ACCfilterT1_PRE MeanResponse2.ACCNeutralHappy6_T2ACCfilterT1_PRE 
    MeanResponse2.ACCNeutralNeutral2_T2ACCfilterT1_PRE MeanResponse2.ACCNeutralNeutral4_T2ACCfilterT1_PRE 
    MeanResponse2.ACCNeutralNeutral6_T2ACCfilterT1_PRE MeanResponse2.ACCAngryAngry2_T2ACCfilterT1_POST 
    MeanResponse2.ACCAngryAngry4_T2ACCfilterT1_POST MeanResponse2.ACCAngryAngry6_T2ACCfilterT1_POST 
    MeanResponse2.ACCAngryHappy2_T2ACCfilterT1_POST MeanResponse2.ACCAngryHappy4_T2ACCfilterT1_POST 
    MeanResponse2.ACCAngryHappy6_T2ACCfilterT1_POST MeanResponse2.ACCAngryNeutral2_T2ACCfilterT1_POST 
    MeanResponse2.ACCAngryNeutral4_T2ACCfilterT1_POST MeanResponse2.ACCAngryNeutral6_T2ACCfilterT1_POST 
    MeanResponse2.ACCHappyAngry2_T2ACCfilterT1_POST MeanResponse2.ACCHappyAngry4_T2ACCfilterT1_POST 
    MeanResponse2.ACCHappyAngry6_T2ACCfilterT1_POST MeanResponse2.ACCHappyHappy2_T2ACCfilterT1_POST 
    MeanResponse2.ACCHappyHappy4_T2ACCfilterT1_POST MeanResponse2.ACCHappyHappy6_T2ACCfilterT1_POST 
    MeanResponse2.ACCHappyNeutral2_T2ACCfilterT1_POST MeanResponse2.ACCHappyNeutral4_T2ACCfilterT1_POST 
    MeanResponse2.ACCHappyNeutral6_T2ACCfilterT1_POST MeanResponse2.ACCNeutralAngry2_T2ACCfilterT1_POST 
    MeanResponse2.ACCNeutralAngry4_T2ACCfilterT1_POST MeanResponse2.ACCNeutralAngry6_T2ACCfilterT1_POST 
    MeanResponse2.ACCNeutralHappy2_T2ACCfilterT1_POST MeanResponse2.ACCNeutralHappy4_T2ACCfilterT1_POST 
    MeanResponse2.ACCNeutralHappy6_T2ACCfilterT1_POST 
    MeanResponse2.ACCNeutralNeutral2_T2ACCfilterT1_POST 
    MeanResponse2.ACCNeutralNeutral4_T2ACCfilterT1_POST 
    MeanResponse2.ACCNeutralNeutral6_T2ACCfilterT1_POST BY PROGRAMA WITH DSOC_02
  /WSFACTOR=Tiempo 2 Polynomial EmoT1 3 Polynomial EmoT2 3 Polynomial Lag 3 Polynomial 
  /CONTRAST(PROGRAMA)=Simple
  /METHOD=SSTYPE(3)
  /PLOT=PROFILE(Lag*PROGRAMA*Tiempo Lag*PROGRAMA*EmoT1 Lag*PROGRAMA*EmoT2 Tiempo*PROGRAMA*EmoT1 
    Tiempo*PROGRAMA*EmoT2 Tiempo*PROGRAMA*Lag)
  /EMMEANS=TABLES(OVERALL) WITH(DSOC_02=MEAN)
  /EMMEANS=TABLES(PROGRAMA) WITH(DSOC_02=MEAN)COMPARE ADJ(BONFERRONI)
  /EMMEANS=TABLES(Tiempo) WITH(DSOC_02=MEAN)COMPARE ADJ(BONFERRONI)
  /EMMEANS=TABLES(EmoT1) WITH(DSOC_02=MEAN)COMPARE ADJ(BONFERRONI)
  /EMMEANS=TABLES(EmoT2) WITH(DSOC_02=MEAN)COMPARE ADJ(BONFERRONI)
  /EMMEANS=TABLES(Lag) WITH(DSOC_02=MEAN)COMPARE ADJ(BONFERRONI)
  /EMMEANS=TABLES(PROGRAMA*Tiempo) WITH(DSOC_02=MEAN)
  /EMMEANS=TABLES(PROGRAMA*EmoT1) WITH(DSOC_02=MEAN)
  /EMMEANS=TABLES(PROGRAMA*EmoT2) WITH(DSOC_02=MEAN)
  /EMMEANS=TABLES(PROGRAMA*Lag) WITH(DSOC_02=MEAN)
  /EMMEANS=TABLES(Tiempo*EmoT1) WITH(DSOC_02=MEAN)
  /EMMEANS=TABLES(Tiempo*EmoT2) WITH(DSOC_02=MEAN)
  /EMMEANS=TABLES(Tiempo*Lag) WITH(DSOC_02=MEAN)
  /EMMEANS=TABLES(EmoT1*EmoT2) WITH(DSOC_02=MEAN)
  /EMMEANS=TABLES(EmoT1*Lag) WITH(DSOC_02=MEAN)
  /EMMEANS=TABLES(EmoT2*Lag) WITH(DSOC_02=MEAN)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT1) WITH(DSOC_02=MEAN)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT2) WITH(DSOC_02=MEAN)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*Lag) WITH(DSOC_02=MEAN)
  /EMMEANS=TABLES(PROGRAMA*EmoT1*EmoT2) WITH(DSOC_02=MEAN)
  /EMMEANS=TABLES(PROGRAMA*EmoT1*Lag) WITH(DSOC_02=MEAN)
  /EMMEANS=TABLES(PROGRAMA*EmoT2*Lag) WITH(DSOC_02=MEAN)
  /EMMEANS=TABLES(Tiempo*EmoT1*EmoT2) WITH(DSOC_02=MEAN)
  /EMMEANS=TABLES(Tiempo*EmoT1*Lag) WITH(DSOC_02=MEAN)
  /EMMEANS=TABLES(Tiempo*EmoT2*Lag) WITH(DSOC_02=MEAN)
  /EMMEANS=TABLES(EmoT1*EmoT2*Lag) WITH(DSOC_02=MEAN)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT1*EmoT2) WITH(DSOC_02=MEAN)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT1*Lag) WITH(DSOC_02=MEAN)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT2*Lag) WITH(DSOC_02=MEAN)
  /EMMEANS=TABLES(PROGRAMA*EmoT1*EmoT2*Lag) WITH(DSOC_02=MEAN)
  /EMMEANS=TABLES(Tiempo*EmoT1*EmoT2*Lag) WITH(DSOC_02=MEAN)
  /EMMEANS=TABLES(PROGRAMA*Tiempo*EmoT1*EmoT2*Lag) WITH(DSOC_02=MEAN)
  /PRINT=DESCRIPTIVE ETASQ OPOWER HOMOGENEITY 
  /CRITERIA=ALPHA(.05)
  /WSDESIGN=Tiempo EmoT1 EmoT2 Lag Tiempo*EmoT1 Tiempo*EmoT2 EmoT1*EmoT2 Tiempo*EmoT1*EmoT2 
    Tiempo*Lag EmoT1*Lag Tiempo*EmoT1*Lag EmoT2*Lag Tiempo*EmoT2*Lag EmoT1*EmoT2*Lag 
    Tiempo*EmoT1*EmoT2*Lag
  /DESIGN=DSOC_02 PROGRAMA.

*********************************************************************** T1 ENSAYOS DOBLES ****************************************************************************************

COMPUTE T1_angry_lag6_PRE=MEAN(MeanResponse2.ACCAngryAngry6_T2ACCfilterT1_PRE,MeanResponse2.ACCAngryHappy6_T2ACCfilterT1_PRE,MeanResponse2.ACCAngryNeutral6_T2ACCfilterT1_PRE).
EXECUTE.

COMPUTE T1_happy_lag6_PRE=MEAN(MeanResponse2.ACCHappyAngry6_T2ACCfilterT1_PRE,MeanResponse2.ACCHappyHappy6_T2ACCfilterT1_PRE,MeanResponse2.ACCHappyNeutral6_T2ACCfilterT1_PRE).
EXECUTE.

COMPUTE T1_neutral_lag6_PRE=MEAN(MeanResponse2.ACCNeutralAngry6_T2ACCfilterT1_PRE,MeanResponse2.ACCNeutralHappy6_T2ACCfilterT1_PRE,MeanResponse2.ACCNeutralNeutral6_T2ACCfilterT1_PRE).
EXECUTE.

COMPUTE T1_angry_lag6_POST=MEAN(MeanResponse2.ACCAngryAngry6_T2ACCfilterT1_POST,MeanResponse2.ACCAngryHappy6_T2ACCfilterT1_POST,MeanResponse2.ACCAngryNeutral6_T2ACCfilterT1_POST).
EXECUTE.

COMPUTE T1_happy_lag6_POST=MEAN(MeanResponse2.ACCHappyAngry6_T2ACCfilterT1_POST,MeanResponse2.ACCHappyHappy6_T2ACCfilterT1_POST,MeanResponse2.ACCHappyNeutral6_T2ACCfilterT1_POST).
EXECUTE.

COMPUTE T1_neutral_lag6_POST=MEAN(MeanResponse2.ACCNeutralAngry6_T2ACCfilterT1_POST,MeanResponse2.ACCNeutralHappy6_T2ACCfilterT1_POST,MeanResponse2.ACCNeutralNeutral6_T2ACCfilterT1_POST).
EXECUTE.

*********************************************************************** T2 ENSAYOS DOBLES ****************************************************************************************

COMPUTE T2_angry_lag6_PRE=MEAN(MeanResponse2.ACCAngryAngry6_T2ACCfilterT1_PRE,MeanResponse2.ACCHappyAngry6_T2ACCfilterT1_PRE,MeanResponse2.ACCNeutralAngry6_T2ACCfilterT1_PRE).
EXECUTE.

COMPUTE T2_happy_lag6_PRE=MEAN(MeanResponse2.ACCAngryHappy6_T2ACCfilterT1_PRE,MeanResponse2.ACCHappyHappy6_T2ACCfilterT1_PRE,MeanResponse2.ACCNeutralHappy6_T2ACCfilterT1_PRE).
EXECUTE.

COMPUTE T2_neutral_lag6_PRE=MEAN(MeanResponse2.ACCAngryNeutral6_T2ACCfilterT1_PRE,MeanResponse2.ACCHappyNeutral6_T2ACCfilterT1_PRE,MeanResponse2.ACCNeutralNeutral6_T2ACCfilterT1_PRE).
EXECUTE.

COMPUTE T2_angry_lag6_POST=MEAN(MeanResponse2.ACCAngryAngry6_T2ACCfilterT1_POST,MeanResponse2.ACCHappyAngry6_T2ACCfilterT1_POST,MeanResponse2.ACCNeutralAngry6_T2ACCfilterT1_POST).
EXECUTE.

COMPUTE T2_happy_lag6_POST=MEAN(MeanResponse2.ACCAngryHappy6_T2ACCfilterT1_POST,MeanResponse2.ACCHappyHappy6_T2ACCfilterT1_POST,MeanResponse2.ACCNeutralHappy6_T2ACCfilterT1_POST).
EXECUTE.

COMPUTE T2_neutral_lag6_POST=MEAN(MeanResponse2.ACCAngryNeutral6_T2ACCfilterT1_POST,MeanResponse2.ACCHappyNeutral6_T2ACCfilterT1_POST,MeanResponse2.ACCNeutralNeutral6_T2ACCfilterT1_POST).
EXECUTE.
